import { Issue, IssuePriority, IssueStatus, IssueType } from "@/types/issue";
import { Role } from "@/types/member";

export const issues: Issue[] = [
  {
    id: 1,
    key: "BOARD-1",
    title: "Update Documentation for API Endpoints",
    description: null,
    assignee: {
      id: 3,
      user: {
        id: 2,
        name: "Alice Smith",
        email: "alice.smith@example.com",
      },
      role: Role.VIEWER,
      joinedOn: new Date("2024-01-21"),
    },
    type: IssueType.TASK,
    status: IssueStatus.DONE,
    priority: IssuePriority.LOW,
    createdOn: "2024-01-20T15:14:18.728544",
    dueOn: "2024-02-01",
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: "2024-01-21T18:42:49.003713",
  },
  {
    id: 2,
    key: "BOARD-2",
    title: "Update UI Design for Homepage",
    description: null,
    assignee: {
      id: 4,
      user: {
        id: 3,
        name: "Michael Brown",
        email: "michael.brown@example.com",
      },
      role: Role.DEVELOPER,
      joinedOn: new Date("2024-01-21"),
    },
    type: IssueType.TASK,
    status: IssueStatus.DONE,
    priority: IssuePriority.MEDIUM,
    createdOn: "2024-01-20T15:15:03.491157",
    dueOn: null,
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: "2024-01-21T18:42:20.275811",
  },
  {
    id: 3,
    key: "BOARD-3",
    title: "Fix Critical Bug in Payment Processing",
    description: null,
    assignee: null,
    type: IssueType.BUG,
    status: IssueStatus.IN_PROGRESS,
    priority: IssuePriority.HIGHEST,
    createdOn: "2024-01-20T15:15:41.511664",
    dueOn: "2024-01-21",
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: null,
  },
  {
    id: 4,
    key: "BOARD-4",
    title: "Cancel Deprecated API Endpoints",
    description: null,
    assignee: {
      id: 2,
      user: {
        id: 4,
        name: "John Doe",
        email: "john.doe@example.com",
      },
      role: Role.VIEWER,
      joinedOn: new Date("2024-01-21"),
    },
    type: IssueType.EPIC,
    status: IssueStatus.DONE,
    priority: IssuePriority.LOWEST,
    createdOn: "2024-01-20T15:16:18.335738",
    dueOn: "2024-02-16",
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: null,
  },
  {
    id: 5,
    key: "BOARD-5",
    title: "Implement Search Functionality",
    description: null,
    assignee: null,
    type: IssueType.EPIC,
    status: IssueStatus.CANCELED,
    priority: IssuePriority.HIGHEST,
    createdOn: "2024-01-20T15:17:07.119415",
    dueOn: "2024-04-07",
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: "2024-01-20T15:17:31.230062",
  },
  {
    id: 6,
    key: "BOARD-6",
    title: "Resolve Cross-Browser Compatibility Issues",
    description: null,
    assignee: {
      id: 3,
      user: {
        id: 2,
        name: "Alice Smith",
        email: "alice.smith@example.com",
      },
      role: Role.VIEWER,
      joinedOn: new Date("2024-01-21"),
    },
    type: IssueType.TASK,
    status: IssueStatus.IN_PROGRESS,
    priority: IssuePriority.HIGH,
    createdOn: "2024-01-20T15:18:18.586667",
    dueOn: "2024-01-20",
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: "2024-01-21T18:42:37.491308",
  },
  {
    id: 7,
    key: "BOARD-7",
    title: "Implement Dark Mode in User Interface",
    description: null,
    type: IssueType.EPIC,
    status: IssueStatus.IN_PROGRESS,
    priority: IssuePriority.LOW,
    createdOn: "2024-01-20T18:08:49.31",
    dueOn: null,
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: "2024-01-21T18:42:32.362142",
  },
  {
    id: 8,
    key: "BOARD-8",
    title: "Optimize Frontend for Mobile Devices",
    description: null,
    assignee: {
      id: 2,
      user: {
        id: 4,
        name: "John Doe",
        email: "john.doe@example.com",
      },
      role: Role.VIEWER,
      joinedOn: new Date("2024-01-21"),
    },
    type: IssueType.TASK,
    status: IssueStatus.CANCELED,
    priority: IssuePriority.MEDIUM,
    createdOn: "2024-01-20T18:42:00.88",
    dueOn: null,
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: null,
  },
  {
    id: 9,
    key: "BOARD-9",
    title: "Investigate Memory Leak in Backend Service",
    description: null,
    assignee: null,
    type: IssueType.BUG,
    status: IssueStatus.TO_DO,
    priority: IssuePriority.HIGH,
    createdOn: "2024-01-20T18:50:12.98",
    dueOn: "2024-01-21",
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: "2024-01-21T18:50:27.736067",
  },
  {
    id: 10,
    key: "BOARD-10",
    title: "Define and Implement Error Handling Strategy",
    description: null,
    assignee: {
      id: 4,
      user: {
        id: 3,
        name: "Michael Brown",
        email: "michael.brown@example.com",
      },
      role: Role.DEVELOPER,
      joinedOn: new Date("2024-01-21"),
    },
    type: IssueType.TASK,
    status: IssueStatus.TO_DO,
    priority: IssuePriority.LOWEST,
    createdOn: "2024-01-20T18:50:55.588",
    dueOn: null,
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: "2024-01-21T19:06:26.580304",
  },
  {
    id: 11,
    key: "BOARD-11",
    title: "Write Unit Tests for Core Modules",
    description: null,
    assignee: {
      id: 3,
      user: {
        id: 2,
        name: "Alice Smith",
        email: "alice.smith@example.com",
      },
      role: Role.VIEWER,
      joinedOn: new Date("2024-01-21"),
    },
    type: IssueType.TASK,
    status: IssueStatus.TO_DO,
    priority: IssuePriority.LOWEST,
    createdOn: "2024-01-20T18:55:11.859",
    dueOn: "2024-02-28",
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: null,
  },
  {
    id: 12,
    key: "BOARD-12",
    title: "Improve Data Encryption for Security",
    description: null,
    assignee: null,
    type: IssueType.TASK,
    status: IssueStatus.IN_PROGRESS,
    priority: IssuePriority.MEDIUM,
    createdOn: "2024-01-20T18:55:57.65",
    dueOn: null,
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: "2024-01-21T18:56:12.04905",
  },
  {
    id: 13,
    key: "BOARD-13",
    title: "Implement Two-Factor Authentication",
    description: null,
    assignee: null,
    type: IssueType.TASK,
    status: IssueStatus.TO_DO,
    priority: IssuePriority.LOW,
    createdOn: "2024-01-21T18:59:57.409245",
    dueOn: "2024-04-03",
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: null,
  },
  {
    id: 14,
    key: "BOARD-14",
    title: "Integrate Real-Time Chat Feature",
    description: null,
    assignee: {
      id: 2,
      user: {
        id: 4,
        name: "John Doe",
        email: "john.doe@example.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-21"),
    },
    type: IssueType.EPIC,
    status: IssueStatus.DONE,
    priority: IssuePriority.HIGH,
    createdOn: "2024-01-20T19:00:23.269",
    dueOn: null,
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: "2024-01-21T19:06:45.12921",
  },
  {
    id: 15,
    key: "BOARD-15",
    title: "Revamp Email Notifications",
    description: null,
    assignee: {
      id: 2,
      user: {
        id: 4,
        name: "John Doe",
        email: "john.doe@example.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-21"),
    },
    type: IssueType.TASK,
    status: IssueStatus.CANCELED,
    priority: IssuePriority.MEDIUM,
    createdOn: "2024-01-20T19:00:23.269",
    dueOn: null,
    createdBy: {
      id: 1,
      user: {
        id: 1,
        name: "admin",
        email: "admin@gmail.com",
      },
      role: Role.OWNER,
      joinedOn: new Date("2024-01-20"),
    },
    updatedOn: "2024-01-21T19:06:45.12921",
  },
];
